#!/bin/sh
# Guard for the one-page publish workflow: refuse to publish a broken or dev-only page.
set -eu

f="one_page/index.html"

if [ ! -f "$f" ]; then
  echo "::error::$f is missing"
  exit 1
fi
if [ -L "$f" ]; then
  echo "::error::$f is a symlink; refusing to publish"
  exit 1
fi
if ! grep -qi '<!doctype html>' "$f"; then
  echo "::error::$f does not contain <!doctype html>"
  exit 1
fi
if grep -qE 'localhost|127\.0\.0\.1|0\.0\.0\.0' "$f"; then
  echo "::error::$f references localhost, 127.0.0.1 or 0.0.0.0"
  exit 1
fi
if ! grep -qF '<link rel="canonical" href="https://jeremyguill.me/">' "$f"; then
  echo "::error::$f lacks the canonical link to https://jeremyguill.me/ (built for another origin?)"
  exit 1
fi
if ! grep -qF 'generated by scripts/build_one_page.py' "$f"; then
  echo "::error::$f is not marked as generated by scripts/build_one_page.py"
  exit 1
fi
echo "$f passed pre-publish checks"
