from __future__ import annotations

import html
import importlib.util
import json
import re
import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "build_one_page.py"
ORIGIN = "https://example.test"


def _load():
    spec = importlib.util.spec_from_file_location("build_one_page", SCRIPT)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["build_one_page"] = module
    spec.loader.exec_module(module)
    return module


bop = _load()


def _img(path: str, alt: str, w: int = 1600, h: int = 900) -> dict:
    return {"url": f"{ORIGIN}/media/public/{path}.webp", "alt": alt, "width": w, "height": h}


def make_data() -> dict:
    return {
        "generated_at": "2026-10-04T00:00:00+00:00",
        "origin": ORIGIN,
        "profile": {
            "display_name": "Test Person",
            "headline": "Builds useful software",
            "summary": "Summary of the profile.",
            "location": None,
            "availability_text": "Open to roles",
            "linkedin_url": "https://www.linkedin.com/in/test",
            "github_url": None,
        },
        "capabilities": [{"title": "Cap A", "body": "Body A"}, {"title": "Cap B", "body": "B"}],
        "projects": [
            {
                "slug": "alpha",
                "title": "Alpha <b>x</b>",
                "summary": "Alpha summary",
                "role": "Developer",
                "stack": ["Python", "SQL"],
                "year": "2020",
                "result_headline": "Saved time",
                "body_html": (
                    '<h2 id="dup">Problem</h2><p>Text <a href="#dup">jump</a></p>'
                    "<table><tr><td>1</td></tr></table>"
                    '<img src="/media/public/x/hero_desktop.webp" alt="in body" '
                    'width="10" height="10">'
                    "<script>alert(1)</script>"
                ),
                "url": f"{ORIGIN}/work/alpha",
                "hero": _img("a/hero", "Alpha hero"),
                "gallery": [_img("a/g1", "Gallery one")],
            },
            {
                "slug": "beta",
                "title": "Beta",
                "summary": "Beta summary",
                "role": None,
                "stack": [],
                "year": None,
                "result_headline": None,
                "body_html": '<h2 id="dup">Problem</h2><table><tr><td>2</td></tr></table>',
                "url": f"{ORIGIN}/work/beta",
                "hero": None,
                "gallery": [],
            },
        ],
        "experience": [
            {
                "organization": "Acme",
                "role": "Engineer",
                "start_date": "2019",
                "end_date": None,
                "summary": "Did things",
                "body_html": "<ul><li>One</li></ul>",
                "logo": _img("l/profile", "Acme logo", 100, 100),
            }
        ],
    }


class _Collect(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.tags: list[tuple[str, dict[str, str | None]]] = []

    def handle_starttag(self, tag, attrs):
        self.tags.append((tag, dict(attrs)))


def parse(html: str) -> list[tuple[str, dict[str, str | None]]]:
    parser = _Collect()
    parser.feed(html)
    return parser.tags


@pytest.fixture(scope="module")
def page() -> str:
    return bop.build_page(make_data(), origin=ORIGIN)


def test_single_h1_and_sections(page):
    tags = parse(page)
    assert [t for t, _ in tags].count("h1") == 1
    ids = [a["id"] for _, a in tags if a.get("id")]
    for section in ("top", "about", "work", "experience", "contact"):
        assert section in ids


def test_no_blog_and_no_email(page):
    low = page.lower()
    assert "/blog" not in low
    assert "latest writing" not in low
    assert "mailto:" not in low
    assert not re.search(r"[\w.+-]+@[\w-]+\.[a-z]{2,}", page)


def test_images_have_alt_size_and_absolute_urls(page):
    imgs = [a for t, a in parse(page) if t == "img"]
    assert len(imgs) >= 6
    for attrs in imgs:
        assert attrs.get("alt"), attrs
        assert attrs.get("width") and attrs.get("height"), attrs
        assert (attrs["src"] or "").startswith(ORIGIN + "/"), attrs


def test_head_metadata(page):
    assert f'<link rel="canonical" href="{ORIGIN}/">' in page
    assert "<title>Test Person | Software and Workflow Portfolio</title>" in page
    assert f"{ORIGIN}/static/assets/fonts/poppins-600.woff2" in page
    assert f"{ORIGIN}/static/assets/fonts/poppins-700.woff2" in page
    assert f"{ORIGIN}/static/assets/fonts/open-sans-var.woff2" in page
    assert f"{ORIGIN}/static/assets/img/og-default.png" in page
    assert "font-display: swap" in page
    assert "generated by scripts/build_one_page.py from" in page


def test_cards_templates_and_dialog(page):
    tags = parse(page)
    links = [a for t, a in tags if t == "a" and a.get("data-case")]
    assert {a["data-case"] for a in links} == {"alpha", "beta"}
    templates = [a for t, a in tags if t == "template"]
    assert {a["data-case"] for a in templates} == {"alpha", "beta"}
    assert any(t == "dialog" and a.get("id") == "case-dialog" for t, a in tags)
    assert page.count("<script") == 1  # the CMS body's <script> is stripped


def test_links_and_rel(page):
    anchors = [a for t, a in parse(page) if t == "a"]
    linkedin = [a for a in anchors if (a.get("href") or "").startswith("https://www.linkedin")]
    assert linkedin and all("noopener" in (a.get("rel") or "") for a in linkedin)
    assert not any("github.com" in (a.get("href") or "") for a in anchors)
    contact = [a for a in anchors if a.get("href") == f"{ORIGIN}/contact"]
    assert contact and "noopener" in (contact[0].get("rel") or "")


def test_body_preserved_tables_wrapped_and_no_duplicate_ids(page):
    assert page.count('<div class="table-scroll" tabindex="0" role="region"') == 2
    ids = [a["id"] for _, a in parse(page) if a.get("id")]
    assert len(ids) == len(set(ids))
    assert "alert(1)" not in page
    assert "<li>One</li>" in page


def test_titles_escaped(page):
    assert "Alpha &lt;b&gt;x&lt;/b&gt;" in page
    assert "<b>x</b>" not in page


def test_no_inline_style_attributes_or_insecure_urls(page):
    assert not re.search(r"<[^>]+\sstyle=", page)
    assert "http://" not in page
    allowed = (ORIGIN, "https://www.linkedin.com", "https://github.com")
    for url in re.findall(r"https://[^\s\"')<>]+", page):
        assert url.startswith(allowed), url


def test_override_replaces_fields_and_ignores_unknown(capsys):
    overrides = {
        "alpha": {
            "title": "New title",
            "summary": "New summary",
            "body_html": "<h2>Fresh</h2><p>Fresh body</p>",
            "stack": ["Access", "VBA"],
            "result_headline": "Better",
        },
        "ghost": {"title": "Nope"},
    }
    html = bop.build_page(make_data(), origin=ORIGIN, overrides=overrides)
    assert "New title" in html and "New summary" in html and "Fresh body" in html
    assert "Alpha summary" not in html
    assert "<li>VBA</li>" in html
    assert "Nope" not in html
    assert "ghost" in capsys.readouterr().err


def test_build_page_is_pure(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    data = make_data()
    before = json.dumps(data, sort_keys=True)
    bop.build_page(data, origin=ORIGIN)
    assert json.dumps(data, sort_keys=True) == before
    assert list(tmp_path.iterdir()) == []


def test_real_pollywog_copy_override_applies():
    overrides = bop.load_copy_overrides()
    assert "pollywog-scheduling-automation" in overrides
    data = make_data()
    data["projects"][0]["slug"] = "pollywog-scheduling-automation"
    html = bop.build_page(data, origin=ORIGIN, overrides=overrides)
    assert "SCREENSHOT PLACEHOLDER" not in html
    assert "The Problem" in html


@pytest.mark.parametrize("content", [None, "{not json"])
def test_cli_fails_cleanly(tmp_path, content, capsys):
    source = tmp_path / "site.json"
    if content is not None:
        source.write_text(content)
    out = tmp_path / "index.html"
    code = bop.main(["--source", str(source), "--output", str(out), "--no-copy-overrides"])
    assert code == 1
    assert not out.exists()
    assert capsys.readouterr().err.strip()


def test_cli_writes_output(tmp_path):
    source = tmp_path / "site.json"
    source.write_text(json.dumps(make_data()))
    out = tmp_path / "nested" / "index.html"
    assert bop.main(
        ["--source", str(source), "--origin", ORIGIN, "--output", str(out),
         "--no-copy-overrides"]
    ) == 0
    assert out.read_text().startswith("<!doctype html>")


def test_script_runs_as_program(tmp_path):
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--source", str(tmp_path / "missing.json"),
         "--output", str(tmp_path / "o.html")],
        capture_output=True, text=True, check=False,
    )
    assert result.returncode == 1
    assert not (tmp_path / "o.html").exists()


def _body(html: str, tables: bool = True) -> str:
    return str(bop._prepare_body(html, ORIGIN, tables=tables))


@pytest.mark.parametrize(
    ("raw", "forbidden"),
    [
        ("<scr<script>ipt>alert(1)", "<script"),
        ("<scr<script></script>ipt>alert(1)</script>", "<script"),
        ("<templ<template>ate>x", "<template"),
        ("<templ<template>ate>x</templ</template>ate>", "template"),
    ],
)
def test_prepare_body_cannot_reassemble_tags(raw, forbidden):
    assert forbidden not in _body(raw).lower()


def test_prepare_body_strips_comments_including_unclosed():
    assert _body("a<!-- hidden -->b") == "ab"
    assert "<b>" not in _body("a<!-- never closed <b>x</b>")
    assert "<scr" not in _body("<scr<!-- x -->ipt>alert(1)</script>").lower()


def test_ids_dropped_but_text_and_attribute_values_preserved():
    assert _body('<h2 id="x">T</h2>') == "<h2>T</h2>"
    code = _body('<pre><code>&lt;div id="x"&gt;</code></pre>')
    assert 'id="x"' in html.unescape(code)
    img = '<img src="https://e.test/a.png" alt="see id=foo here">'
    assert 'alt="see id=foo here"' in _body(img)
    assert 'alt="href=/x"' in _body('<img src="https://e.test/a.png" alt="href=/x">')


def test_alt_attribute_cannot_break_out():
    raw = '<p><img src="https://e.test/m.png" alt="a id="></p><p>" onerror=alert(1) x</p>'
    out = _body(raw)
    imgs = [a for t, a in parse(out) if t == "img"]
    assert imgs and imgs[0]["alt"] == "a id="
    assert not any("onerror" in a for _, a in parse(out))


@pytest.mark.parametrize(
    "raw",
    [
        "<img src=x onerror=alert(1)>",
        "<svg onload=alert(1)></svg>",
        '<a href="javascript:alert(1)">x</a>',
        '<a href="  jav&#x09;ascript:alert(1)">x</a>',
        '<iframe src="https://evil.test"></iframe>',
        "<style>body{display:none}</style>",
        '<meta http-equiv="refresh" content="0;url=https://evil.test">',
        "<script>alert(1)</script>",
        "<scr<script>ipt>alert(1)</script>",
        "<templ<template>ate>x</template>",
        "<p>ok</p><!-- unclosed <img src=x onerror=alert(1)>",
    ],
)
def test_untrusted_body_is_neutralised(raw):
    out = _body(raw)
    tags = parse(out)
    names = {t for t, _ in tags}
    assert not names & {"script", "svg", "iframe", "style", "meta", "template"}
    for _, attrs in tags:
        assert not any(k.startswith("on") for k in attrs)
        for key in ("href", "src"):
            value = (attrs.get(key) or "").lower()
            assert not value.startswith(("javascript:", "data:", "vbscript:"))
    assert "alert(1)" not in out or "<" not in out.split("alert(1)")[0][-20:]


def test_legit_content_survives_and_urls_absolutised():
    raw = (
        '<h2>Head</h2><p><strong>b</strong> <a href="https://e.test/x">l</a></p>'
        '<ul><li>i</li></ul><table><tr><td>1</td></tr></table>'
        '<img src="/media/public/a.webp" alt="A" width="5" height="5">'
        '<a href="/work/x">w</a><a href="rel/path">r</a><a href="//evil.test/">p</a>'
        '<a href="/\\evil.test">q</a>'
    )
    out = _body(raw, tables=True)
    for frag in ("<h2>Head</h2>", "<strong>b</strong>", "<li>i</li>", "<table>"):
        assert frag in out
    hrefs = [a.get("href") for t, a in parse(out) if t == "a"]
    assert f"{ORIGIN}/work/x" in hrefs and "https://e.test/x" in hrefs
    assert not any(h and ("evil" in h or h == "rel/path") for h in hrefs)
    srcs = [a.get("src") for t, a in parse(out) if t == "img"]
    assert srcs == [f"{ORIGIN}/media/public/a.webp"]
    assert 'tabindex="0" role="region" aria-label="Scrollable table"' in out


def test_unquoted_root_relative_urls_are_absolutised():
    out = _body("<img src=/y.png alt=a>")
    assert [a["src"] for t, a in parse(out) if t == "img"] == [f"{ORIGIN}/y.png"]
    assert "href" not in _body("<a href=//cdn.test/x>x</a>")
    assert "<a" not in _body("<p>&lt;a href=/z&gt;</p>")


def test_focus_return_prefers_title_link():
    js = (ROOT / "scripts" / "one_page" / "app.js").read_text(encoding="utf-8")
    assert 'querySelector(`h3 a[data-case="${attr}"]`)' in js


def test_dark_button_override_follows_base_rule():
    css = (ROOT / "scripts" / "one_page" / "style.css").read_text(encoding="utf-8")
    base = css.index(".button-primary { background: var(--blue)")
    dark = css.index(".button-primary { color: var(--paper); }")
    assert dark > base


def test_project_url_off_origin_raises():
    data = make_data()
    data["projects"][0]["url"] = "javascript:alert(1)"
    with pytest.raises(bop.BuildError, match="url"):
        bop.build_page(data, origin=ORIGIN)


def test_social_url_must_be_https():
    data = make_data()
    data["profile"]["linkedin_url"] = "javascript:alert(1)"
    data["profile"]["github_url"] = "http://github.com/x"
    out = bop.build_page(data, origin=ORIGIN)
    assert "javascript:" not in out and "github.com/x" not in out
    assert ">LinkedIn<" not in out and ">GitHub<" not in out


def test_images_must_come_from_origin():
    data = make_data()
    data["projects"][0]["hero"]["url"] = "https://evil.test/h.webp"
    data["projects"][0]["gallery"][0]["url"] = "javascript:x"
    data["experience"][0]["logo"]["url"] = "https://evil.test/l.webp"
    out = bop.build_page(data, origin=ORIGIN)
    assert "evil.test" not in out and "javascript:" not in out
    assert 'class="case-hero"' not in out


def test_export_origin_mismatch_fails_unless_allowed():
    data = make_data()
    data["origin"] = "https://other.test"
    with pytest.raises(bop.BuildError, match="origin"):
        bop.build_page(data, origin=ORIGIN)
    assert ORIGIN in bop.build_page(data, origin=ORIGIN, allow_origin_mismatch=True)


def test_cli_origin_mismatch_flag(tmp_path, capsys):
    data = make_data()
    data["origin"] = "https://other.test"
    source = tmp_path / "site.json"
    source.write_text(json.dumps(data))
    out = tmp_path / "o.html"
    argv = ["--source", str(source), "--origin", ORIGIN, "--output", str(out),
            "--no-copy-overrides"]
    assert bop.main(argv) == 1
    assert not out.exists() and "origin" in capsys.readouterr().err
    assert bop.main([*argv, "--allow-origin-mismatch"]) == 0
    assert out.exists()


def test_source_comment_never_leaks_local_paths():
    local = bop.build_page(make_data(), origin=ORIGIN, source="/mnt/x/y/site.json")
    assert "/mnt/x" not in local and "from site.json on" in local
    remote = bop.build_page(make_data(), origin=ORIGIN, source="https://h.test/api/s.json")
    assert "from https://h.test/api/s.json on" in remote


def test_cli_reports_template_errors_cleanly(tmp_path, capsys):
    data = make_data()
    del data["projects"][0]["title"]
    source = tmp_path / "site.json"
    source.write_text(json.dumps(data))
    out = tmp_path / "o.html"
    argv = ["--source", str(source), "--origin", ORIGIN, "--output", str(out),
            "--no-copy-overrides"]
    assert bop.main(argv) == 1
    assert not out.exists() and "error" in capsys.readouterr().err


def test_applied_overrides_are_reported(capsys):
    bop.build_page(make_data(), origin=ORIGIN, overrides={"alpha": {"summary": "S"}})
    assert "applied copy override: alpha" in capsys.readouterr().err


def test_pre_blocks_are_keyboard_focusable():
    out = _body("<pre><code>x = 1</code></pre>")
    assert '<pre tabindex="0" role="region" aria-label="Code sample">' in out


def _norm(text: str) -> str:
    return " ".join(html.unescape(re.sub(r"<[^>]+>", " ", text)).split())


def test_homepage_copy_matches_main_site_home_template():
    """The strings the one-pager reproduces must still exist in the main site's home.html."""
    home = _norm((ROOT / "src/portfolio/templates/public/home.html").read_text("utf-8"))
    data = make_data()
    data["profile"]["summary"] = ""
    page = bop.build_page(data, origin=ORIGIN)
    fallback = re.search(r'<meta name="description" content="([^"]*)"', page)
    assert fallback and _norm(fallback.group(1)) in home

    checked = 0
    for marker in ('<section id="about"', '<section class="split-detail">',
                   '<section id="work"', '<section class="principle-section">',
                   '<section id="contact"'):
        start = page.index(marker)
        block = page[start:page.index("</section>", start)]
        block = re.sub(r"<article.*?</article>", "", block, flags=re.DOTALL)
        for _, inner in re.findall(r"<(h2|h3|p)[^>]*>(.*?)</\1>", block, flags=re.DOTALL):
            text = _norm(inner)
            if text:
                assert text in home, text
                checked += 1
    assert checked >= 12
